import _ from 'lodash';
import ensure from '@redux-beacon/ensure';

import { actionToFormEvent } from './actionToEvents';
import { isValidEvent } from './utils';

const eventsMap = {
  '@@redux-form/INITIALIZE': actionToFormEvent('Initialize'),
  '@@redux-form/START_SUBMIT': actionToFormEvent('Submit'),
  '@@redux-form/SET_SUBMIT_SUCCEEDED': actionToFormEvent('Submit Success'),
  '@@redux-form/SET_SUBMIT_FAILED': actionToFormEvent('Submit Failure')
};

//wrap each event (in eventsMap) with ensure to validate later.
// The callback (isValidEvent) will be given an event (generated by actionToFormEvent) based on which
// we'll decide whether that particular event should be sent to gtm.
export default _.mapValues(eventsMap, (val) => ensure(isValidEvent, val));
